# Removing Apache2 from any machine in host file
---
- hosts: testmachine
  become: yes
  vars:
   packages:
   - apache2
   - apache2-utils
   - apache2.2-bin
   - apache2-common

  tasks:
  - name: stopping apache2 service
    service:
     name: apache2
     state: stopped
  - name: removing {{ packages }}
    apt:
     name: "{{ packages }}"
     state: absent
 



