# Install Mongo
---
# target hosts updated
- hosts: testmachine
  become: yes
  tasks:
    - name: Install mongo now!!
      apt:
        name=mongodb
        state=latest
        update_cache=yes
    - name: Start Mongo sevice
      service:
        name=mongodb
        state=started





